# Sealos DevBox 配置文件
# 刷刷题项目云端开发环境
apiVersion: devbox.sealos.io/v1alpha1
kind: DevBox
metadata:
  name: shuashuati-devbox
  namespace: default
spec:
  # 开发环境配置
  image: "ghcr.io/labring/devbox-node:18"
  
  # 资源配置
  resource:
    cpu: "2000m"
    memory: "4Gi"
    storage: "20Gi"
  
  # 端口配置
  ports:
    - name: admin-web
      port: 5173
      protocol: TCP
      description: "管理端开发服务器"
    - name: miniprogram
      port: 5174
      protocol: TCP
      description: "小程序端开发服务器"
    - name: server
      port: 8080
      protocol: TCP
      description: "后端API服务"
  
  # 环境变量
  env:
    - name: NODE_ENV
      value: "development"
    - name: VITE_API_BASE_URL
      value: "http://localhost:8080/api"
    - name: SUPABASE_URL
      value: "https://lvafyknbbxmcatbmzeij.supabase.co"
    - name: SUPABASE_ANON_KEY
      value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2YWZ5a25iYnhtY2F0Ym16ZWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTk1OTksImV4cCI6MjA2OTE3NTU5OX0.U9nIK4Z_Dc-A_LxpSJdAWNX0YSo3h6x6lvNtVqfI6hk"
  
  # 启动脚本
  command:
    - "/bin/bash"
    - "-c"
    - |
      # 安装项目依赖
      echo "正在安装项目依赖..."
      
      # 安装管理端依赖
      cd /workspace/admin-web
      npm install
      
      # 安装小程序端依赖
      cd /workspace/miniprogram
      npm install
      
      # 安装Go环境（如果需要本地开发后端）
      curl -L https://go.dev/dl/go1.21.0.linux-amd64.tar.gz | tar -C /usr/local -xz
      export PATH=$PATH:/usr/local/go/bin
      
      echo "开发环境准备完成！"
      echo "管理端开发服务器: http://localhost:5173"
      echo "小程序端开发服务器: http://localhost:5174"
      echo "后端API服务: http://localhost:8080"
      
      # 保持容器运行
      tail -f /dev/null
  
  # 工作目录
  workingDir: "/workspace"
  
  # 挂载配置
  volumes:
    - name: workspace
      mountPath: "/workspace"
      size: "10Gi"
  
  # 网络配置
  network:
    type: "NodePort"
    
  # 自动保存配置
  autoSave:
    enabled: true
    interval: "5m"
    
  # SSH配置
  ssh:
    enabled: true
    port: 22
    
  # VS Code配置
  vscode:
    enabled: true
    extensions:
      - "Vue.volar"
      - "ms-vscode.vscode-typescript-next"
      - "bradlc.vscode-tailwindcss"
      - "golang.go"
      - "ms-vscode.vscode-json"
      - "esbenp.prettier-vscode"