# Sealos 部署配置 - 后端服务
# 刷刷题项目后端API服务部署到Sealos平台
apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: default
type: Opaque
data:
  # Base64编码的环境变量
  SUPABASE_URL: aHR0cHM6Ly9sdmFmeWtuYmJ4bWNhdGJtemVpai5zdXBhYmFzZS5jbw==
  SUPABASE_SERVICE_ROLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW14MllXWjVhMjVpWW5odFkyRjBZbTE2WldscUlpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMxTXpVNU9UVTVPVGtzSW1WNGNDSTZNakEyT1RFM05UVTVPVGw5LmZuMmhfWk1aeFNUUjAzdnpfRFNBV2E3R0hpSFFnaHNmSlZiemZYalhYSGc=
  JWT_SECRET: YzJWaGJHOXpMWE5sWTNKbGRDMXJaWGt0Wm05eUxYTm9kV0Z6YUhWaGRHa3RjSEp2YW1WamRBPT0=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: default
data:
  PORT: "8080"
  GIN_MODE: "release"
  CORS_ORIGINS: "https://shuashuati-admin.cloud.sealos.io,https://shuashuati-app.cloud.sealos.io"
  LOG_LEVEL: "info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app: server
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: golang:1.21-alpine
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: PORT
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: GIN_MODE
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: CORS_ORIGINS
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: SUPABASE_URL
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: JWT_SECRET
        workingDir: /app
        command:
        - sh
        - -c
        - |
          echo "开始构建并运行后端服务..."
          go mod download
          go build -o main .
          ./main
        volumeMounts:
        - name: source-code
          mountPath: /app
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: source-code
        configMap:
          name: server-source

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
  labels:
    app: server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://shuashuati-admin.cloud.sealos.io,https://shuashuati-app.cloud.sealos.io"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  tls:
  - hosts:
    - shuashuati-server.cloud.sealos.io
    secretName: server-tls
  rules:
  - host: shuashuati-server.cloud.sealos.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-service
            port:
              number: 8080

---
# 水平自动扩缩容
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80